/**
 * Created by Damodar Bashyal
 * Date: 1/10/11
 * Time: 3:24 PM
 * Package: codefight cms share buttons
 * Doc: http://codefight.org/blog/0/119/Social-Share-Plugin
 */
;(function(a,e){a.fn.extend({cfShare:function(b){function l(a){a=a.toString().toLowerCase().replace(/(?:^|\s)\w/g,function(a){return a.toUpperCase()});return"cf"+a}function m(){var c;a.each(b.shareClients,function(){c=l(this);try{d[c](),a("#cfShareClientsFloat").append('<span class="sepFloat"></span>')}catch(b){console.log(c+" is not a function")}})}function j(){a("div#cfShareStyle").append('<style type="text/css">#sharebox .cfshare {z-index: 1000;}.fb_iframe_widget iframe {left: 0;position: absolute;top: 0;z-index: 1;}</style>')}
function g(c){b.animate===!0?f.stop().animate({top:c}):f.css({padding:b.sharePadding,top:a(e).scrollTop()>b.startTop?0:b.startTop,position:"fixed",margin:b.marginFixed,left:"50%"})}function h(){if(a(e).width()-b.pageWidth>135){var c='<style type="text/css">#sharebox {background: #fff;position: relative;-moz-border-radius: 5px;border-radius: 5px;text-align: center;}#sharebox .cfshare {left: '+b.shareLeft+"px;width: "+b.shareWidth+"px;padding: 5px;position: absolute;top: 0;background-color: #FAFAFA;border: "+
b.border+";}#sharebox .cfshare:hover {background-color: "+b.bgColor+";box-shadow: 0 0 4px rgba(0, 0, 0, 0.1);}.cfBtnFloatDownload {bottom: 0;display: block;height: 22px;margin: 10px 0 0;position: absolute;width: 71px;}.cfBtnFloatDownload {display: block;margin: 10px 0 0;}.cfBtnFloatDownload a {background: #DEDEDE;border: 1px solid #FAFAFA;color: #FBFBFB;display: block;font-size: 11px;text-decoration: none;}.cfBtnFloatDownload a:hover {color: #693;}.sepFloat{display: block;height: 5px;overflow: hidden;}.addthisFrap{display: block; text-align: center; margin: 0 auto; width: 50px;}#cfShareClientsFloat a.addthis_button_tweet{width: 70px;}.at300b,.at300b:hover{opacity: 1;}.cfBtnFloatRdt{}#cfShareClientsFloat{padding: 0 0 20px;}.cfBtnFloatHide{}.cfBtnFloatHide a {display: block;background: #eee;font-size: 11px;line-height: 14px;margin: 0px 0 2px;}</style>";
a("div#cfShareStyle").html(c);j();a("#cfShareClientsFloat:hidden").show();a("#cfShareClientsOriginal:visible").hide();c=d.offset().top;switch(b.fromPosition){case "top":a(e).scrollTop()>b.startTop?g(a(e).scrollTop()-c+b.topPadding):g(b.startTop-c);break;default:a(e).scrollTop()>c?g(a(e).scrollTop()-c+b.topPadding):g(0)}}else f.removeAttr("style"),c='<style type="text/css">#sharebox {background: #fff;position: relative;-moz-border-radius: 5px;border-radius: 5px;margin-bottom: 15px;}#sharebox .cfshare {padding: 5px;background-color: '+
b.bgColor+";border: "+b.border+";min-height: 20px;}#sharebox .cfshare:hover {background-color: "+b.bgColor+";box-shadow: 0 0 4px rgba(0, 0, 0, 0.1);}.cfBtnOrig{float: left;}.addthisOrap{margin-right: 10px;}.at300b,.at300b:hover{opacity: 1;}.cfBtnOrigRdt, .cfBtnOrigLn{float:left;}</style>",a("div#cfShareStyle").html(c),j(),a("#cfShareClientsOriginal:hidden").show(),a("#cfShareClientsFloat:visible").hide();f.css({overflow:"visible"})}function k(a,b,d){a="<script type=\"text/javascript\">(function(){var cfgb = document.createElement('script'); cfgb.type = 'text/javascript';"+
(b==null||d=="1"?"cfgb.async = true;":"")+"cfgb.src = ('https:' == document.location.protocol ? 'https://' : 'http://')+'"+a+"';";a+=b==null?"var cfs = document.getElementsByTagName('script')[0]; cfs.parentNode.insertBefore(cfgb,cfs);":"var cfs = document.getElementById('"+b+"'); cfs.appendChild(cfgb);";a+="})()<\/script>";return a}var n={addthisId:"",enableRemove:!0,enableFloat:!0,animate:!0,bgColor:"#fff",fromPosition:"original",marginFixed:"0 7px 4px -572px",border:"1px solid #E5E5E5",pageWidth:980,
shareClients:[],shareLeft:-84,sharePadding:5,shareWidth:70,startTop:70,topPadding:0,url:encodeURIComponent(e.location)},b=a.extend(n,b),d=this,f=d.find(".cfshare"),i=f.html('<div id="cfShareClients"><div id="cfShareClientsFloat" style="display: none;"></div><div id="cfShareClientsOriginal" style="display: none;"></div></div><div id="cfShareStyle"></div><div id="cfShareJs"></div>').find("#cfShareJs");a(e).scroll(function(){h()});a(e).resize(function(){h()});d.cfFacebook=function(){a("#cfShareClientsOriginal").append('<a class="addthis_button_facebook_like cfBtnOrig" fb:like:layout="button_count"></a>');
b.enableFloat&&a("#cfShareClientsFloat").append('<a class="addthis_button_facebook_like cfBtnFloat" fb:like:layout="box_count"></a>')};d.cfFacebooksend=function(){a("#cfShareClientsOriginal").append('<a class="addthis_button_facebook_send cfBtnOrig"></a>');b.enableFloat&&a("#cfShareClientsFloat").append('<a class="addthis_button_facebook_send cfBtnFloat"></a>')};d.cfTwitter=function(){a("#cfShareClientsOriginal").append('<a class="addthis_button_tweet cfBtnOrig"></a>');b.enableFloat&&a("#cfShareClientsFloat").append('<a class="addthis_button_tweet cfBtnFloat" tw:count="vertical"></a>')};
d.cfGoogleplusone=function(){a("#cfShareClientsOriginal").append('<a class="addthis_button_google_plusone cfBtnOrig" g:plusone:size="medium"></a>');b.enableFloat&&a("#cfShareClientsFloat").append('<a class="addthis_button_google_plusone cfBtnFloat" g:plusone:size="tall"></a>')};d.cfAddthis=function(){a("#cfShareClientsOriginal").append('<a class="addthis_counter addthis_pill_style cfBtnOrig addthisOrap"></a>');b.enableFloat&&a("#cfShareClientsFloat").append('<a class="addthis_counter cfBtnFloat addthisFrap"></a>')};
d.cfDigg=function(){i.append('<script src="http://widgets.digg.com/buttons.js" type="text/javascript"><\/script>');a("#cfShareClientsOriginal").append('<a class="DiggThisButton DiggCompact cfBtnOrig"></a>');b.enableFloat&&a("#cfShareClientsFloat").append('<a class="DiggThisButton DiggMedium cfBtnFloat"></a>')};d.cfReddit=function(){a("#cfShareClientsOriginal").append('<div class="cfBtnOrigRdt"><a href="http://www.reddit.com/submit?url='+b.url+'" onclick="window.location = \'http://www.reddit.com/submit?url=\' + encodeURIComponent(window.location); return false"><img src="http://www.reddit.com/static/spreddit7.gif" alt="submit to reddit" border="0"></a></div><span class="sepOrig"></span>');
b.enableFloat&&a("#cfShareClientsFloat").append('<div class="cfBtnFloatRdt" id="cfBtnFloatRdt">').append(k("www.reddit.com/static/button/button2.js","cfBtnFloatRdt","1")).append("</div>")};d.cfLinkedin=function(){i.append(k("platform.linkedin.com/in.js",null));a("#cfShareClientsOriginal").append('<div class="cfBtnOrigLn" id="cfBtnOrigLn"><script type="IN/Share" data-counter="right"><\/script></div><span class="sepOrig"></span>');b.enableFloat&&a("#cfShareClientsFloat").append('<div class="cfBtnFloatLn">').append('<script type="IN/Share" data-counter="top"><\/script>').append("</div>")};
i.append('<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid='+b.addthisId+'"><\/script>');a(document).ready(function(){m();h()});b.enableFloat&&a("#cfShareClientsFloat").append('<div class="cfBtnFloatDownload"><a target="_blank" href="http://codefight.org/blog/0/119/Social-Share-Plugin?ref='+e.location.hostname+'">share bar</a></div>');b.enableRemove&&a("#cfShareClientsFloat").prepend('<div class="cfBtnFloatHide"><a href="javascript:void(0);" onclick="jQuery(\'#sharebox\').remove();">remove</a></div>')}})})(jQuery,
window);
